services:
  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: target
      POSTGRES_USER: target
      POSTGRES_INITDB_ARGS: "-E UTF8"
      POSTGRES_DB: target_rifle_scores
    volumes:
      - db-data:/var/lib/postgresql/data/
  web:
    build: .
    #command: python database_setup.py
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
volumes:
  db-data: